//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenFu.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GenFu.Properties.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AB
        ///BC
        ///MB
        ///NB
        ///NL
        ///NT
        ///NS
        ///NU
        ///ON
        ///PE
        ///QC
        ///SK
        ///YT.
        /// </summary>
        public static string CanadianProvinceAbreviations {
            get {
                return ResourceManager.GetString("CanadianProvinceAbreviations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ontario
        ///Quebec
        ///Nova Scotia
        ///New Brunswick
        ///Manitoba
        ///British Columbia
        ///Prince Edward Island
        ///Saskatchewan
        ///Alberta
        ///Newfoundland and Labrador
        ///Northwest Territories
        ///Yukon
        ///Nunavut.
        /// </summary>
        public static string CanadianProvinceNames {
            get {
                return ResourceManager.GetString("CanadianProvinceNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brandon
        ///Carberry
        ///Winnipeg
        ///Calgary
        ///Edmonton
        ///New York
        ///New Jersey
        ///Paris
        ///London
        ///Amsterdam
        ///Vancouver
        ///Toronto
        ///Houston
        ///Hanover
        ///Little Rock
        ///Abbotsford
        ///Armstrong
        ///Burnaby
        ///Campbell River
        ///Castlegar
        ///Chilliwack
        ///Colwood
        ///Coquitlam
        ///Courtenay
        ///Cranbrook
        ///Dawson Creek
        ///Duncan
        ///Enderby
        ///Fernie
        ///Fort St. John
        ///Grand Forks
        ///Greenwood
        ///Kamloops
        ///Kelowna
        ///Kimberley
        ///Langford
        ///Langley
        ///Merritt
        ///Nanaimo
        ///Nelson
        ///New Westminster
        ///North Vancouver
        ///Parksville
        ///Penticton
        ///Pitt Meadows
        ///Port Alberni
        ///Port Coquitlam [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CityNames {
            get {
                return ResourceManager.GetString("CityNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AGT
        ///KIO
        ///GGR
        ///Smith
        ///Orion
        ///GMC
        ///Ford
        ///Hundai
        ///Pacific
        ///Atlantic
        ///Mother&apos;s
        ///Frank&apos;s
        ///Berkshire Hathaway
        ///Pepsi
        ///Coca-cola.
        /// </summary>
        public static string CompanyNames {
            get {
                return ResourceManager.GetString("CompanyNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gmail.com
        ///hotmail.com
        ///live.com
        ///gmx.com
        ///microsoft.com
        ///shaw.ca
        ///telus.net
        ///rogers.ca
        ///att.com.
        /// </summary>
        public static string DomainNames {
            get {
                return ResourceManager.GetString("DomainNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abacavir
        ///Aciclovir
        ///Acyclovir
        ///Adefovir
        ///Amantadine
        ///Amprenavir
        ///Ampligen
        ///Arbidol
        ///Atazanavir
        ///Edoxudine
        ///Efavirenz
        ///Emtricitabine
        ///Enfuvirtide
        ///Entecavir
        ///Ibacitabine
        ///Imunovir
        ///Idoxuridine
        ///Imiquimod
        ///Indinavir
        ///Inosine
        ///Integrase inhibitor
        ///Interferon type III
        ///Interferon type II
        ///Interferon type I
        ///Interferon
        ///Telaprevir
        ///Tenofovir
        ///Tenofovir disoproxil
        ///Tipranavir
        ///Trifluridine
        ///Trizivir
        ///Tromantadine
        ///Truvada
        ///Zalcitabine
        ///Zanamivir (Relenza)
        ///Zidovudine.
        /// </summary>
        public static string Drugs {
            get {
                return ResourceManager.GetString("Drugs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angela
        ///Ang
        ///Angie
        ///Violet
        ///Broderick
        ///Lorrie
        ///Adella
        ///Jason
        ///Silvia
        ///Colby
        ///Raymundo
        ///Lekisha
        ///Kandra
        ///Carlie
        ///Kecia
        ///James
        ///Lakeshia
        ///Ozella
        ///Liberty
        ///Victorina
        ///Khalilah
        ///Cathey
        ///Gabriel
        ///Terica
        ///John
        ///Bettye
        ///Darron
        ///Judi
        ///Melisa
        ///Kermit
        ///Mark
        ///Danyel
        ///Petronila
        ///Rosalinda
        ///Shalonda
        ///Pilar
        ///Joel
        ///Cary
        ///Leroy
        ///Jillian
        ///Stan
        ///Milissa
        ///Marvis
        ///Chris
        ///Emelda
        ///Beulah
        ///Lorenza
        ///Sammy
        ///Peter
        ///Keith
        ///Kevin
        ///Andrew
        ///Brandon
        ///Olivia
        ///Diedra
        ///Cherlyn
        ///Josefa
        ///Hettie
        ///Kaycee
        ///Sommer
        ///Leslie
        ///Jerica
        ///Ross
        ///Tarra
        ///Ja [rest of string was truncated]&quot;;.
        /// </summary>
        public static string FirstNames {
            get {
                return ResourceManager.GetString("FirstNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agender
        ///Androgyne
        ///Androgynous
        ///Bigender
        ///Cis
        ///Cisgender
        ///Cis Female
        ///Cis Male
        ///Cis Man
        ///Cis Woman
        ///Cisgender Female
        ///Cisgender Male
        ///Cisgender Man
        ///Cisgender Woman
        ///Female to Male
        ///FTM
        ///Gender Fluid
        ///Gender Nonconforming
        ///Gender Questioning
        ///Gender Variant
        ///Genderqueer
        ///Intersex
        ///Male to Female
        ///MTF
        ///Neither
        ///Neutrois
        ///Non-binary
        ///Other
        ///Pangender
        ///Trans
        ///Trans*
        ///Trans Female
        ///Trans* Female
        ///Trans Male
        ///Trans* Male
        ///Trans Man
        ///Trans* Man
        ///Trans Person
        ///Trans* Person
        ///Trans Woman
        ///Trans* Woman
        ///Transfemini [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Genders {
            get {
                return ResourceManager.GetString("Genders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounting
        ///Aircraft
        ///Alcohol
        ///Automotive
        ///Banking
        ///Chemical
        ///Cosmetic
        ///Electronics
        ///Entertainment
        ///Fashion
        ///Fishing
        ///Food
        ///Glass
        ///Growth Hacking
        ///Healthcare
        ///Hot Dogs
        ///Insurance
        ///Investments
        ///Leathermaking
        ///Manufactured Goods
        ///Manufacturing
        ///Marketing
        ///Media
        ///Military
        ///Mining
        ///Nuclear
        ///Packaging
        ///Petrochemical
        ///Petroleum
        ///Plastics
        ///Plumbing
        ///Professional Wrestling
        ///Pulp and Paper
        ///Rail
        ///Real Estate
        ///Recycling
        ///Rubber
        ///Security
        ///Service
        ///Shipping
        ///Shoes
        ///Space
        ///Sports
        ///Steel
        ///Sugar
        ///Tabacco
        ///Tea
        ///Telecommun [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Industries {
            get {
                return ResourceManager.GetString("Industries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sugar
        ///Spice
        ///Everything nice
        ///Yummy yummy egg nog
        ///Salt
        ///Pepper
        ///Olive Oil
        ///Basil
        ///Chicken Broth
        ///Cloves
        ///Garlic
        ///Onion
        ///Eggs
        ///Tomatoes
        ///Chicken Thighs
        ///Chicken Breast
        ///Pork Ribs
        ///Mozzarella Cheese
        ///Parmesan Cheese
        ///Butter
        ///Nutmeg
        ///Fettuccine
        ///Parsley
        ///Orange Zest
        ///Whipping Cream
        ///Cranberries
        ///Tomatoe Paste
        ///Mushrooms
        ///Cambozola Cheese
        ///Green Onions
        ///Flour
        ///Bran
        ///Green Beans
        ///Lima Beans
        ///Vinegar
        ///Mustard
        ///Water
        ///Raisins
        ///Liver
        ///Potato
        ///Corn
        ///Tabasco
        ///Cashews
        ///Celery
        ///Ground Beef
        ///Rib Steak
        ///Asparagus
        ///Cook [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Ingredients {
            get {
                return ResourceManager.GetString("Ingredients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abrasions and &apos;Road Rash&apos;
        ///ACL Injury
        ///ACL Injuries and Skiing
        ///Achilles Tendonitis
        ///Achilles Tendon Ruptures
        ///Adhesive Capsulitis (Frozen Shoulder)
        ///Altitude Illness
        ///Ankle Anatomy and Physiology
        ///Ankle Sprains
        ///Ankle Fracture
        ///Ankle Injuries
        ///Anorexia
        ///Anterior and Posterior Cruciate Ligament Injury
        ///Arthritis of the Shoulder
        ///Athlete&apos;s Foot (Tinea Pedis)
        ///Back Pain
        ///Baseball Injuries
        ///Basketball Injuries
        ///Blisters
        ///Bulimia
        ///Burner / Stinger Syndrome
        ///Bursitis 
        ///Calf Strain
        ///Carpal Tunnel Syndrome
        ///Cartil [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Injuries {
            get {
                return ResourceManager.GetString("Injuries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iginla
        ///Smith
        ///Verstraete
        ///Johnson
        ///Daeninck
        ///Williams
        ///Choi
        ///Jones
        ///Getzlaff
        ///Brown
        ///Ratzlaff
        ///Radcliff
        ///Davis
        ///Brugger
        ///Miller
        ///Mc Vicar
        ///Wilson
        ///Moore
        ///Perry
        ///Taylor
        ///White
        ///Harris
        ///Thomas
        ///Jackson
        ///Garcia
        ///Martinez
        ///Martin
        ///Clark
        ///Rodriguez
        ///Yarobi
        ///Thompson
        ///MacKenzie
        ///Anderson
        ///MacDonald
        ///Robinson
        ///Lewis
        ///Pearson
        ///Lee
        ///Young
        ///Hernandez
        ///King
        ///Walker
        ///Hall
        ///Allen
        ///Chambers
        ///Wright
        ///Lopez
        ///Martinez
        ///Hill
        ///Scott
        ///Green
        ///Adams
        ///Baker
        ///Gonzalez
        ///Nelson
        ///Carter
        ///Mitchell
        ///Perez
        ///Roberts
        ///Turner
        ///Phillips
        ///C [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LastNames {
            get {
                return ResourceManager.GetString("LastNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lorem
        ///ipsum        ///dolor        ///sit        ///amet
        ///consectetur
        ///adipiscing        ///elit        ///ut        ///aliquam        ///purus        ///sit        ///amet        ///luctus        ///venenatis        ///lectus        ///magna        ///fringilla        ///urna        ///porttitor        ///rhoncus        ///dolor        ///purus        ///non        ///enim        ///praesent        ///elementum        ///facilisis        ///leo        ///vel        ///fringilla        ///est        ///ullamcorper        ///eget        ///nulla        ///facilisi        ///etiam        ///dignissim        ///diam        ///quis        ///enim        ///lobortis        ///scelerisque        ///fermentum        ///dui        ///faucibus        ///in        ///ornare        ///quam        ///viverra        ///orci        ///sagittis        ///eu        ///volutpat        ///odio        ///facilisis        ///mauris        ///sit        ///amet        ///massa        ///vitae        ///tortor        ///condimentum        ///lacinia        ///quis        ///vel        ///eros        ///donec        ///ac        ///odio        ///tempor        ///orci        ///dapibus        ///ultrices        ///in        ///iaculis        ///n [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Lorem {
            get {
                return ResourceManager.GetString("Lorem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cardiac stress test
        ///Electrocardiography
        ///Electroencephalography
        ///Electrocorticography
        ///Electromyography
        ///Electroneuronography
        ///Electronystagmography
        ///Electrooculography
        ///Electroretinography
        ///Endoluminal capsule monitoring
        ///Endoscopy
        ///Colonoscopy
        ///Colposcopy
        ///Cystoscopy
        ///Gastroscopy
        ///Laparoscopy
        ///Laryngoscopy
        ///Ophthalmoscopy
        ///Otoscopy
        ///Sigmoidoscopy
        ///Esophageal motility study
        ///Evoked potential
        ///Magnetoencephalography
        ///Medical imaging
        ///Angiography
        ///Aortography
        ///Cerebral angiography
        ///Coronary angiography
        ///Lym [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MedicalProcedures {
            get {
                return ResourceManager.GetString("MedicalProcedures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thriller
        ///Back in Black
        ///The Dark Side of the Moon
        ///The Bodyguard
        ///Bad
        ///Bat Out of Hell
        ///Their Greatest Hits (1971–1975)
        ///Saturday Night Fever
        ///Rumours
        ///Come On Over
        ///Jagged Little Pill
        ///Dangerous
        ///Sgt. Pepper&apos;s Lonely Hearts Club Band
        ///Falling into You
        ///Music Box
        ///Dirty Dancing
        ///Let&apos;s Talk About Love
        ///Abbey Road
        ///Baby One More Time
        ///Born in the U.S.A.
        ///Brothers in Arms
        ///Appetite for Destruction
        ///In-A-Gadda-Da-Vida
        ///Titanic: Music from the Motion Picture
        ///The Immaculate Collection
        ///Nevermind
        ///The Wall
        ///Supe [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MusicAlbums {
            get {
                return ResourceManager.GetString("MusicAlbums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Santana
        ///Gloria Estefan
        ///R.E.M.
        ///Van Halen
        ///Lillix
        ///Limblifter
        ///Lime
        ///The Lincolns
        ///Lioness
        ///Little Caesar and the Consuls
        ///Little Girls
        ///Live on Arrival
        ///LiveonRelease
        ///LMDS
        ///Local Rabbits
        ///Loco Locass
        ///Lola Dutronic
        ///Longing for Dawn
        ///The Look People
        ///Lost &amp; Profound
        ///Lost Dakotas
        ///The Most Serene Republic
        ///Mother Mother
        ///Motion Ensemble
        ///Farm Fresh
        ///Mountain City Four
        ///The Mountains and the Trees
        ///Moxy
        ///Moxy Früvous
        ///Mr. Pine
        ///MSTRKRFT
        ///Mudmen
        ///The Musical Box
        ///My Darkest Days
        ///The Mynah Birds
        ///Mystery
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MusicArtists {
            get {
                return ResourceManager.GetString("MusicArtists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mr. 
        ///Mrs.
        ///Ms.
        ///Miss.
        ///Doctor
        ///Dr.
        ///General
        ///Master
        ///Princess
        ///Air Marshall.
        /// </summary>
        public static string PersonTitles {
            get {
                return ResourceManager.GetString("PersonTitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbey Court
        ///Aberdeen Street
        ///Adams Street
        ///Adelphi Street
        ///Adler Place
        ///Agate Court
        ///Ainslie Street
        ///Aitken Place
        ///Alabama Avenue
        ///Albany Avenue
        ///Albee Square
        ///Albemarle Road
        ///Albemarle Terrace
        ///Alice Court
        ///Allen Avenue
        ///Alton Place
        ///Amber Street
        ///Amboy Street
        ///Amersfort Place
        ///Amherst Street
        ///Amity Street
        ///Anchorage Place
        ///Anna Court
        ///Anthony Street
        ///Apollo Street
        ///Applegate Court
        ///Argyle Road
        ///Arion Place
        ///Arkansas Drive
        ///Arlington Avenue
        ///Arlington Place
        ///Ash Street
        ///Ashford Street
        ///Ashland Place
        ///Aste [rest of string was truncated]&quot;;.
        /// </summary>
        public static string StreetNames {
            get {
                return ResourceManager.GetString("StreetNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attourney Accidentally Sues Himself
        ///County to Pay $250,000 to Advertise Lack of Funds
        ///Caskets Found as Workers Demolish Mausoleum
        ///Supreme Court Rules Some of 10 Commandments Not Okay
        ///Federal Agents Raid Gun Shop, Find Weapons
        ///Child Wins Gun from Fundraiser
        ///Statistics Show Teenage Pregnancy Drops Dramatically After Age 19
        ///Utah Poison Control Center Asks People to not Consume Poison
        ///Most Earthquake Damage is Caused by Shaking
        ///City Unsure Why the Sewer Smells
        ///State Prisons to Replace Easy-Open Locks        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Titles {
            get {
                return ResourceManager.GetString("Titles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AL
        ///AK
        ///AZ
        ///AR
        ///CA
        ///CO
        ///CT
        ///DE
        ///DC
        ///FL
        ///GA
        ///HI
        ///ID
        ///IL
        ///IN
        ///IA
        ///KS
        ///KY
        ///LA
        ///ME
        ///MD
        ///MA
        ///MI
        ///MN
        ///MS
        ///MO
        ///MT
        ///NE
        ///NV
        ///NH
        ///NJ
        ///NM
        ///NY
        ///NC
        ///ND
        ///OH
        ///OK
        ///OR
        ///PA
        ///RI
        ///SC
        ///SD
        ///TN
        ///TX
        ///UT
        ///VT
        ///VA
        ///WA
        ///WV
        ///WI
        ///WY
        ///.
        /// </summary>
        public static string USAStateAbreviations {
            get {
                return ResourceManager.GetString("USAStateAbreviations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to California
        ///Texas
        ///New York
        ///Florida
        ///Illinois
        ///Pennsylvania
        ///Ohio
        ///Georgia
        ///Michigan
        ///North Carolina
        ///New Jersey
        ///Virginia
        ///Washington
        ///Massachusetts
        ///Arizona
        ///Indiana
        ///Tennessee
        ///Missouri
        ///Maryland
        ///Wisconsin
        ///Minnesota
        ///Colorado
        ///Alabama
        ///South Carolina
        ///Louisiana
        ///Kentucky
        ///Oregon
        ///Oklahoma
        ///Puerto Rico
        ///Connecticut
        ///Iowa
        ///Mississippi
        ///Arkansas
        ///Kansas
        ///Utah
        ///Nevada
        ///New Mexico
        ///Nebraska
        ///West Virginia
        ///Idaho
        ///Hawaii
        ///Maine
        ///New Hampshire
        ///Rhode Island
        ///Montana
        ///Delaware
        ///South Dakota
        ///Alaska
        ///North Dak [rest of string was truncated]&quot;;.
        /// </summary>
        public static string USAStateNames {
            get {
                return ResourceManager.GetString("USAStateNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to year
        ///way
        ///day
        ///thing
        ///man
        ///world
        ///life
        ///hand
        ///part
        ///child
        ///eye
        ///womn
        ///place
        ///work
        ///week
        ///case
        ///point
        ///government
        ///company
        ///number
        ///group
        ///problem
        ///fact
        ///Dreamcatcher
        ///vegan
        ///hella
        ///master
        ///cleanse
        ///pop-up
        ///street
        ///art
        ///terry
        ///richardson
        ///DIY
        ///ennui
        ///pork
        ///belly
        ///craft
        ///beer
        ///helvetica
        ///direct
        ///trade
        ///Tofu
        ///jean
        ///shorts
        ///vinyl
        ///synth
        ///Polaroid
        ///occupy
        ///ennui
        ///craft
        ///beer
        ///cray
        ///bushwick
        ///cosby
        ///sweater
        ///kogi
        ///semiotics
        ///mustache
        ///Cardigan
        ///gentrify
        ///freegan
        ///keffiyeh
        ///authentic
        ///PBR
        ///fixie
        ///marfa
        ///photo
        ///bo [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Words {
            get {
                return ResourceManager.GetString("Words", resourceCulture);
            }
        }
    }
}
